# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/dave/openMixR/fpga/constraints/pins.xdc

# IP: ip/dsi_pll/dsi_pll.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dsi_pll || ORIG_REF_NAME==dsi_pll}]
